-- 修复 admins 表结构
-- 添加缺少的字段

-- 检查并添加 last_login_at 字段
ALTER TABLE admins 
ADD COLUMN IF NOT EXISTS last_login_at DATETIME NULL AFTER role,
ADD COLUMN IF NOT EXISTS last_login_ip VARCHAR(45) NULL AFTER last_login_at,
ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP AFTER last_login_ip,
ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

-- 查看表结构
DESCRIBE admins;
